#!/usr/bin/env ruby
# frozen_string_literal: true
require 'irb'
require 'irb/completion'
require 'rubygems'
require "pathname"
require 'pp'

$LOAD_PATH.unshift File.expand_path("../lib", Pathname.new(__FILE__).dirname)

require "bundler/setup"

# You can add fixtures and/or initialization code here to make experimenting
# with your gem easier. You can also use a different console, if you like.

# (If you use this, don't forget to add pry to your Gemfile!)
# require "pry"
# Pry.start

require "irb"
IRB.start(__FILE__)
