#!/bin/sh

set -eu

./bin/brew update --force --quiet
chmod -R go-w ./bin/brew/share/zsh 2>/dev/null
git pull --quiet --tags
git stash list

#brew tap "${BREW_OWNER}/tap"
sudo chmod -R g+w /Library/Developer /Library/Java /Library/Perl /Library/Python /Library/Ruby
sudo chown -R :admin /Library/Developer /Library/Java /Library/Perl /Library/Python /Library/Ruby

# TODO: PROBAR CON EL HOMEBREW_CORE TAMBIEN CLONE. y el ignore ! y con la veriable exportada.

